# Generated by Django 5.0 on 2024-01-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('kualitas', models.ImageField(null=True, upload_to='')),
                ('Harga', models.CharField(max_length=255)),
            ],
        ),
    ]
